import type { Locale } from './posts';

/** Decorative psychology vocabulary for the hover-reveal background, per locale. */
export const BACKGROUND_WORDS: Record<Locale, string[]> = {
	pt: [
		'Empatia', 'Memória', 'Atenção', 'Cognição', 'Perceção', 'Emoção', 'Resiliência', 'Hábito',
		'Motivação', 'Inconsciente', 'Identidade', 'Ansiedade', 'Autoestima', 'Intuição', 'Curiosidade',
		'Aprendizagem', 'Comportamento', 'Personalidade', 'Consciência', 'Terapia', 'Bem-estar',
		'Dissonância cognitiva', 'Vinculação', 'Pertença', 'Luto', 'Gratidão', 'Nostalgia',
		'Força de vontade', 'Condicionamento', 'Reflexão', 'Imaginação', 'Catarse', 'Sonhos',
		'Neuroplasticidade', 'Enviesamento', 'Atenção plena', 'Fluxo', 'Projeção', 'Repressão',
		'Arquétipo', 'Heurística', 'Autocompaixão', 'Sono', 'Stress', 'Regulação emocional',
	],
	en: [
		'Empathy', 'Memory', 'Attention', 'Cognition', 'Perception', 'Emotion', 'Resilience', 'Habit',
		'Motivation', 'Unconscious', 'Identity', 'Anxiety', 'Self-esteem', 'Intuition', 'Curiosity',
		'Learning', 'Behavior', 'Personality', 'Consciousness', 'Therapy', 'Well-being',
		'Cognitive dissonance', 'Attachment', 'Belonging', 'Grief', 'Gratitude', 'Nostalgia',
		'Willpower', 'Conditioning', 'Reflection', 'Imagination', 'Catharsis', 'Dreams',
		'Neuroplasticity', 'Bias', 'Mindfulness', 'Flow', 'Projection', 'Repression',
		'Archetype', 'Heuristics', 'Self-compassion', 'Sleep', 'Stress', 'Emotional regulation',
	],
	es: [
		'Empatía', 'Memoria', 'Atención', 'Cognición', 'Percepción', 'Emoción', 'Resiliencia', 'Hábito',
		'Motivación', 'Inconsciente', 'Identidad', 'Ansiedad', 'Autoestima', 'Intuición', 'Curiosidad',
		'Aprendizaje', 'Conducta', 'Personalidad', 'Conciencia', 'Terapia', 'Bienestar',
		'Disonancia cognitiva', 'Apego', 'Pertenencia', 'Duelo', 'Gratitud', 'Nostalgia',
		'Fuerza de voluntad', 'Condicionamiento', 'Reflexión', 'Imaginación', 'Catarsis', 'Sueños',
		'Neuroplasticidad', 'Sesgo', 'Atención plena', 'Flujo', 'Proyección', 'Represión',
		'Arquetipo', 'Heurística', 'Autocompasión', 'Sueño', 'Estrés', 'Regulación emocional',
	],
	fr: [
		'Empathie', 'Mémoire', 'Attention', 'Cognition', 'Perception', 'Émotion', 'Résilience', 'Habitude',
		'Motivation', 'Inconscient', 'Identité', 'Anxiété', 'Estime de soi', 'Intuition', 'Curiosité',
		'Apprentissage', 'Comportement', 'Personnalité', 'Conscience', 'Thérapie', 'Bien-être',
		'Dissonance cognitive', 'Attachement', 'Appartenance', 'Deuil', 'Gratitude', 'Nostalgie',
		'Volonté', 'Conditionnement', 'Réflexion', 'Imagination', 'Catharsis', 'Rêves',
		'Neuroplasticité', 'Biais', 'Pleine conscience', 'Flux', 'Projection', 'Refoulement',
		'Archétype', 'Heuristique', 'Autocompassion', 'Sommeil', 'Stress', 'Régulation émotionnelle',
	],
	de: [
		'Empathie', 'Gedächtnis', 'Aufmerksamkeit', 'Kognition', 'Wahrnehmung', 'Emotion', 'Resilienz', 'Gewohnheit',
		'Motivation', 'Unbewusstes', 'Identität', 'Angst', 'Selbstwert', 'Intuition', 'Neugier',
		'Lernen', 'Verhalten', 'Persönlichkeit', 'Bewusstsein', 'Therapie', 'Wohlbefinden',
		'Kognitive Dissonanz', 'Bindung', 'Zugehörigkeit', 'Trauer', 'Dankbarkeit', 'Nostalgie',
		'Willenskraft', 'Konditionierung', 'Reflexion', 'Vorstellungskraft', 'Katharsis', 'Träume',
		'Neuroplastizität', 'Verzerrung', 'Achtsamkeit', 'Flow', 'Projektion', 'Verdrängung',
		'Archetyp', 'Heuristik', 'Selbstmitgefühl', 'Schlaf', 'Stress', 'Emotionsregulation',
	],
	hi: [
		'सहानुभूति', 'स्मृति', 'ध्यान', 'संज्ञान', 'धारणा', 'भावना', 'लचीलापन', 'आदत',
		'प्रेरणा', 'अवचेतन', 'पहचान', 'चिंता', 'आत्म-सम्मान', 'अंतर्ज्ञान', 'जिज्ञासा',
		'सीखना', 'व्यवहार', 'व्यक्तित्व', 'चेतना', 'चिकित्सा', 'कल्याण',
		'संज्ञानात्मक असंगति', 'लगाव', 'अपनत्व', 'शोक', 'कृतज्ञता', 'पुरानी यादें',
		'इच्छाशक्ति', 'अनुकूलन', 'चिंतन', 'कल्पना', 'रेचन', 'सपने',
		'न्यूरोप्लास्टिसिटी', 'पूर्वाग्रह', 'सजगता', 'प्रवाह', 'प्रक्षेपण', 'दमन',
		'आद्यरूप', 'आत्म-करुणा', 'नींद', 'तनाव', 'भावनात्मक नियमन',
	],
	ja: [
		'共感', '記憶', '注意', '認知', '知覚', '感情', 'レジリエンス', '習慣',
		'動機づけ', '無意識', 'アイデンティティ', '不安', '自尊心', '直感', '好奇心',
		'学習', '行動', '性格', '意識', 'セラピー', 'ウェルビーイング',
		'認知的不協和', '愛着', '帰属意識', '悲嘆', '感謝', '郷愁',
		'意志力', '条件づけ', '内省', '想像力', 'カタルシス', '夢',
		'神経可塑性', 'バイアス', 'マインドフルネス', 'フロー', '投影', '抑圧',
		'元型', 'ヒューリスティック', 'セルフ・コンパッション', '睡眠', 'ストレス', '感情調整',
	],
	ar: [
		'التعاطف', 'الذاكرة', 'الانتباه', 'الإدراك المعرفي', 'الإدراك', 'العاطفة', 'المرونة النفسية', 'العادة',
		'الدافع', 'اللاوعي', 'الهوية', 'القلق', 'تقدير الذات', 'الحدس', 'الفضول',
		'التعلّم', 'السلوك', 'الشخصية', 'الوعي', 'العلاج', 'الرفاهية',
		'التنافر المعرفي', 'التعلّق', 'الانتماء', 'الحزن', 'الامتنان', 'الحنين',
		'قوة الإرادة', 'الاشتراط', 'التأمل', 'الخيال', 'التنفيس', 'الأحلام',
		'اللدونة العصبية', 'التحيّز', 'اليقظة الذهنية', 'التدفق', 'الإسقاط', 'الكبت',
		'النمط الأصلي', 'التعاطف مع الذات', 'النوم', 'التوتر', 'تنظيم المشاعر',
	],
};
